### PR TITLE
Add configurable model and before save callback

### PR DESCRIPTION
**Pull request by bmichotte**
This PR adds two elements

1) Ability to configure the *invitation* model using `InvitationModel` in the config file
2) Adds a nullable `beforeSave` callback to `invite`. This allows to add some parameters to the *invitation* model or do some validation/other before saving the invitation.
In our application, we needed to add some non-nullable parameters to the invitation, so we can do something like this 
```php
Invite::invite($to, Auth::user()->id, Carbon::now()->addYear(1),
                      function(/* InvitationModel  */ $invitation) use ($someValue) {
      $invitation->someParam = $someValue;
});
```

### CODE REVIEW

**Comment by junaidnasir** [comment]
thanks for pr, can you please update readme accordingly

**Comment by smoothlikejazz** [comment]
This is a great feature, I also needed this to be able to have the user send an optional message along with the invite.

**Comment by bmichotte** [comment]
Oh... I never received the message from @junaidnasir. I though this PR was dead ;)

I'll add a word in the readme asap !

**Comment by bmichotte** [comment]
Readme updated

**Comment by bmichotte** [comment]
Thanks for merging @junaidnasir !

**Pull request merged**
